# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gNyQfJFkNPnPfUIWUJ5HYD_Y1YxPPDw7
"""

from tensorflow import keras
import tensorflow as tf
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
from numpy import expand_dims

from google.colab import drive
drive.mount('/gdrive')

img=load_img('/gdrive/My Drive/IMAGE datasets/sample1.jpg')
data=img_to_array(img)
sample=expand_dims(data,0)
datagenerator=ImageDataGenerator(width_shift_range=[-500,500],height_shift_range=2,rotation_range=60,zoom_range=[0.5,1],horizontal_flip=True,vertical_flip=True,brightness_range=[0.2,1])
iterator=datagenerator.flow(sample,batch_size=1)
for i in range(9):
  plt.subplot(330+1+i)
  batch=iterator.next()
  image = batch[0].astype('uint8')
  plt.imshow(image)
  plt.show()

save_here = '/grive/My Drive/IMAGE Datasets2'
datagenerator.fit(img)
for x, val in zip(datagenerator.flow(img,                    
        save_to_dir=save_here,     
         save_prefix='aug',        
        save_format='jpg'),batch_size=10) :
        break

